<?php

namespace Database\Seeders;

use App\Models\Author;
use App\Models\Binding;
use App\Models\Book;
use App\Models\Category;
use App\Models\Language;
use App\Models\Product;
use App\Models\Publisher;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;


// FOTKY BRANE Z: https://www.martinus.sk/

class BookSeeder extends Seeder
{
    public function run(): void
    {
        // nacitavanie dat do pomocnych poli
        $categories = Category::all()->keyBy('name');
        $publishers = Publisher::all()->keyBy('name');
        $languages = Language::all()->keyBy('name');
        $bindings = Binding::all()->keyBy('name');


        $books = [
            [
                'name' => 'Hobbit',
                'author' => ['J.R.R.', 'Tolkien'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601234',
                'price' => 14.90,
                'stock_count' => 25,
                'year' => 2020,
                'pages_num' => 304,
                'weight' => 0.45,
                'width' => 14.00,
                'height' => 21.00,
                'depth' => 2.50,
                'images' => ['images/books/hobbit.webp'],
                'description' => 'Jedno z najslávnejších diel svetovej literatúry, určené čitateľom všetkých vekových kategórií.

                Hobbiti sú pokojamilovní ľudkovia, žijúci v útulných jaskynkách. Sú menší ako trpaslíci, svojími vlastnosťami pripomínajú ľudí, no ich svet je rozprávkový. Dobrodružné rozprávanie o hrdinstve a statočnosti, v ktorom napokon víťazí dobro nad zlom.
                Dotlač nového, nezmeneného vydania prekladu Viktora Krupu.',
            ],
            [
                'name' => 'Pán prsteňov: Spoločenstvo prsteňa',
                'author' => ['J.R.R.', 'Tolkien'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601235',
                'price' => 18.90,
                'stock_count' => 20,
                'year' => 2021,
                'pages_num' => 432,
                'weight' => 0.62,
                'width' => 14.50,
                'height' => 21.50,
                'depth' => 3.20,
                'images' => ['images/books/pp_prsten.webp'],
                'description' => 'Tento príbeh narastal pri rozprávaní, až sa stal dejinami Veľkej vojny o Prsteň a obsahuje mnoho pohľadov do ešte starodávnejších dejín, ktoré mu predchádzali - napísal v predslove k druhému vydaniu J. R. R. Tolkien o tejto vari najznámejšej knižnej trilógii minulého storočia. Čarovný svet elfov a hobitov je paralelným svetom ""veľkých ľudí"". Jeho hlavnou témou je Prsteň ako ohnivko, ktoré ho púta k Hobitovi. Proti akýmkoľvek alegóriám sa autor bránil a všetky možné posolstvá a vnútorné významy spájané s jeho knihou sa mu zo srdca protivili. Preto je túto knihu potrebné chápať ako najobľúbenejšie dejiny pradávneho veku a nijako inak. Knihu preložil Otakar Kořínek.

                Všetkým filmovým fanúšikom dávame do pozornosti aj film na DVD s názvom Pán prsteňov: Spoločenstvo prsteňa, ktorý bol natočený podľa tohto titulu.',
            ],
            [
                'name' => 'Pán prsteňov: Dve veže',
                'author' => ['J.R.R.', 'Tolkien'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601236',
                'price' => 18.90,
                'stock_count' => 18,
                'year' => 2021,
                'pages_num' => 448,
                'weight' => 0.64,
                'width' => 14.50,
                'height' => 21.50,
                'depth' => 3.30,
                'images' => ['images/books/pp_veze.webp'],
                'description' => '',
            ],
            [
                'name' => 'Pán prsteňov: Návrat kráľa',
                'author' => ['J.R.R.', 'Tolkien'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601237',
                'price' => 18.90,
                'stock_count' => 17,
                'year' => 2021,
                'pages_num' => 460,
                'weight' => 0.66,
                'width' => 14.50,
                'height' => 21.50,
                'depth' => 3.40,
                'images' => ['images/books/pp_navrat.webp'],
                'description' => '',
            ],
            [
                'name' => 'Harry Potter a Kameň mudrcov',
                'author' => ['Joanne', 'Rowling'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601238',
                'price' => 13.90,
                'stock_count' => 30,
                'year' => 2019,
                'pages_num' => 328,
                'weight' => 0.38,
                'width' => 13.50,
                'height' => 20.50,
                'depth' => 2.20,
                'images' => ['images/books/hp_mudrc.webp'],
                'description' => '',
            ],
            [
                'name' => 'Harry Potter a Väzeň z Azkabanu',
                'author' => ['Joanne', 'Rowling'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601240',
                'price' => 14.90,
                'stock_count' => 24,
                'year' => 2020,
                'pages_num' => 392,
                'weight' => 0.43,
                'width' => 13.50,
                'height' => 20.50,
                'depth' => 2.50,
                'images' => ['images/books/hp_vazen.webp'],
                'description' => 'Keď v tme s treskotom pristane pri Harrym Rytiersky autobus, začne sa tým preňho ďalší školský rok, ktorý ani zďaleka nie je obyčajný. Sirius Black, šialený zločinec a prívrženec lorda Voldemorta, je na úteku a údajne ide práve po Harrym. Profesorka Trelawneyová na prvej Harryho hodine veštenia vidí v jeho čajových lístkoch znamenie smrti. Zo všetkého najstrašnejší sú však asi dementori, ktorí strážia školský areál a svojím bozkom vysávajú duše...

Vďaka nádherným plnofarebným ilustráciám a jedinečným interaktívnym prvkom z dielne grafického štúdia MinaLima bude toto originálne vydanie tretieho pokračovania kníh o Harrym Potterovi ozdobou knižnice všetkých čitateľov a fanúšikov.',
            ],
            [
                'name' => 'Zaklínač: Posledné želanie',
                'author' => ['Andrzej', 'Sapkowski'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Čeština',
                'publisher' => 'Albatros Media',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601241',
                'price' => 15.50,
                'stock_count' => 16,
                'year' => 2018,
                'pages_num' => 288,
                'weight' => 0.36,
                'width' => 13.80,
                'height' => 20.80,
                'depth' => 2.00,
                'images' => ['images/books/zaklinac_posledne_zelanie.webp'],
                'description' => 'Blyskáča posadne mocný džin oslobodený z fľaše. Geralt sa preto vydáva do mesta Rinda, kde prosí o pomoc čarodejnicu Yennefer. Tá síce Blyskáča vylieči, ale zároveň očaruje Geralta a s jeho pomocou sa pomstí ľuďom v meste. Yennefer chce džina znova vyvolať a chytiť ho, lenže to sa jej nepodarí, pretože Geraltovi splnil iba dve priania a nemôže odísť, kým nesplní aj to tretie.',
            ],
            [
                'name' => 'Zaklínač: Meč osudu',
                'author' => ['Andrzej', 'Sapkowski'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Čeština',
                'publisher' => 'Albatros Media',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601242',
                'price' => 15.50,
                'stock_count' => 15,
                'year' => 2018,
                'pages_num' => 320,
                'weight' => 0.38,
                'width' => 13.80,
                'height' => 20.80,
                'depth' => 2.10,
                'images' => ['images/books/zaklinac_mec_osudu.webp'],
                'description' => '',
            ],
            [
                'name' => 'Letopisy Narnie',
                'author' => ['C.S.', 'Lewis'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Slovenčina',
                'publisher' => 'Tatran',
                'binding' => 'E-kniha',
                'isbn' => '9788055601243',
                'price' => 19.90,
                'stock_count' => 14,
                'year' => 2017,
                'pages_num' => 768,
                'weight' => 0.85,
                'width' => 15.50,
                'height' => 22.50,
                'depth' => 4.50,
                'images' => ['images/books/letopisy.webp'],
                'description' => '',

            ],
            [
                'name' => 'Percy Jackson: Zlodej blesku',
                'author' => ['Rick', 'Riordan'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'English',
                'publisher' => 'Albatros Media',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601244',
                'price' => 12.90,
                'stock_count' => 22,
                'year' => 2016,
                'pages_num' => 377,
                'weight' => 0.39,
                'width' => 13.00,
                'height' => 19.80,
                'depth' => 2.40,
                'images' => ['images/books/pj_blesk.webp'],
                'description' => 'CHLAPEC - POLOBOH - HRDINA Volám sa Percy Jackson. Až doteraz som si myslel, že som obyčajný chalan, ktorého v najhoršom prípade čaká vyhodenie zo školy… Zistil som však, že môj otec je jeden z hlavných bohov na Olympe, moja učiteľka sa premenila na krvilačnú príšeru a môj najlepší kamarát Grover je satyr! Odrazu na mňa číhajú kadejaké monštrá zo starých gréckych povestí a vládca bohov Zeus ma podozrieva, že som mu ukradol blesk - jeho najmocnejšiu zbraň. Aby som zachránil seba a celé ľudstvo, musím dokázať svoju nevinu a nájsť pravého zlodeja aj ukradnutý blesk. Pomôžeš mi? Bude to však nebezpečné, tak sa potom nesťažuj, že som ťa nevaroval! Prvá časť svetovo úspešnej fantasy série.',
            ],
            [
                'name' => 'Alchymista',
                'author' => ['Paulo', 'Coelho'],
                'category' => 'Romány',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601245',
                'price' => 10.90,
                'stock_count' => 35,
                'year' => 2018,
                'pages_num' => 192,
                'weight' => 0.22,
                'width' => 12.50,
                'height' => 19.50,
                'depth' => 1.40,
                'images' => ['images/books/alchymista.webp'],
                'description' => 'Podmanivý román, ktorý očarí jednoduchosťou a múdrosťou, nadchol ľudí na celom svete. Alchymista rozpráva príbeh andalúzskeho pastiera Santiaga, ktorý sa vybral z rodného Španielska do egyptskej púšte hľadať poklad ukrytý v pyramídach. Cestou stretne Cigánku, muža, ktorý sám seba nazýva kráľom, a alchymistu. Všetci mu ukážu smer, no nik netuší, kde sa poklad nachádza ani to, či Santiago zdolá všetky prekážky. Hľadanie svetského pokladu sa napokon zmení na objav pokladu vo vlastnom vnútri. Svieži, pútavý, no najmä hlboko ľudský príbeh Santiaga predstavuje večné svedectvo o sile snov meniť všetko navôkol a o dôležitosti načúvania svojmu srdcu.',
            ],
            [
                'name' => 'Malý princ',
                'author' => ['Antoine', 'de Saint-Exupéry'],
                'category' => 'Romány',
                'language' => 'Slovenčina',
                'publisher' => 'Slovart',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601246',
                'price' => 9.90,
                'stock_count' => 40,
                'year' => 2026,
                'pages_num' => 112,
                'weight' => 0.20,
                'width' => 12.00,
                'height' => 18.00,
                'depth' => 1.20,
                'images' => ['images/books/maly_princ.webp'],
                'description' => '„Dobre vidíme iba srdcom. To hlavné je očiam neviditeľné.“

Pôvabná knižka nielen pre deti, ale pre všetkých, ktorí chcú deťom porozumieť. Toto dielko dosiahlo svetový úspech a dnes patrí do základného fondu svetovej literatúry. Jeho hodnota a krása nespočíva len v peknom rozprávkovom príbehu, ale hlavne v myšlienkach, ktoré ako vzácne kamienky vytvárajú obraz tých najkrajších ľudských vlastností...
Knižka vychádza v novom preklade.',
            ],
            [
                'name' => 'Pýcha a predsudok',
                'author' => ['Jane', 'Austen'],
                'category' => 'Romány',
                'language' => 'Slovenčina',
                'publisher' => 'Tatran',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601247',
                'price' => 11.50,
                'stock_count' => 19,
                'year' => 2017,
                'pages_num' => 320,
                'weight' => 0.31,
                'width' => 13.00,
                'height' => 20.00,
                'depth' => 2.00,
                'images' => ['images/books/pycha_predsudok.webp'],
                'description' => 'Od veľkého nečakaného úspechu prvého knižného vydania v roku 1813 sa dielo Pýcha a predsudok stalo populárnym po celom svete a očarilo milióny čitateľov. Autorka Jane Austen nazvala román „svojím drahým dieťaťom“ a jeho hrdinku Elizabeth „najrozkošnejším stvorením, aké sa kedy v knihách objavilo“. Ľúbostné peripetie medzi nezávislou slečnou Bennetovou a hrdým pánom Darcym sú skvostnou ukážkou dvorenia a spoločenských pomerov na začiatku 19. storočia. Hrdinovia románu na jeho stránkach roztancujú delikátnu štvorylku plnú flirtovania, pôvabu a dôvtipu, ktorá poteší a pobaví nielen priaznivcov románovej tvorby regentského obdobia v Anglicku. K slovenskému čitateľovi sa kniha dostáva v novom preklade.',
            ],
            [
                'name' => 'Jane Eyrová',
                'author' => ['Charlotte', 'Brontë'],
                'category' => 'Romány',
                'language' => 'Čeština',
                'publisher' => 'Tatran',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601248',
                'price' => 12.90,
                'stock_count' => 12,
                'year' => 2016,
                'pages_num' => 416,
                'weight' => 0.49,
                'width' => 14.00,
                'height' => 21.00,
                'depth' => 2.80,
                'images' => ['images/books/jane_eyre.webp'],
                'description' => 'Sirota Jane Eyrová nemala ľahké detstvo. V Lowoodskej škole pre chudobné dievčatá a pod vplyvom svojej nevľúdnej tety okúsila trpkú osamelosť i krutosť. To však len posilnilo jej odhodlanie nájsť v živote šťastie a vlastnú cestu. Mohla by to dokázať vďaka práci guvernantky, ktorú získala v sídle Thornfield.
Majiteľ sídla a Janin zamestnávateľ, zádumčivý a svojrázny pán Rochester, je charizmatický muž a zdá sa, že ani Jane mu nie je ľahostajná. Múry sídla však ukrývajú temné tajomstvo, ktoré Janine nežné city podrobí skúške. Rozhodne sa ostať v Thornfielde a čeliť následkom alebo poslúchne svoje presvedčenie, hoci to znamená opustiť milovaného muža?

Čiastočne autobiografický román je kritikou viktoriánskej spoločnosti a zároveň zobrazuje osudovú lásku klasického gotického príbehu doplnením nových realistických motívov.',
            ],
            [
                'name' => 'Búrlivé výšiny',
                'author' => ['Emily', 'Brontë'],
                'category' => 'Romány',
                'language' => 'Slovenčina',
                'publisher' => 'Tatran',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601249',
                'price' => 11.90,
                'stock_count' => 14,
                'year' => 2015,
                'pages_num' => 304,
                'weight' => 0.30,
                'width' => 13.00,
                'height' => 20.00,
                'depth' => 1.90,
                'images' => ['images/books/burlive_vysiny.webp'],
                'description' => 'Pán Lockwood, nový nájomník usadlosti Drozdovo, nachádza v nehostinných vresoviskách yorkshirského panstva pokoj od ruchu spoločnosti. Jednej noci je nútený vyhľadať prístrešok v neďalekom sídle Búrlivé výšiny. Tam sa dozvedá o dramatických udalostiach z minulosti, o vášnivom vzťahu siroty Heathcliffa a Catherine Earnshawovej, dcéry pána domu, ktorá pred láskou uprednostnila spoločenské očakávania. Zatrpknutý Heathcliff je po zrade odhodlaný pomstiť sa nasledujúcej generácii a prinútiť nevinných dedičov čeliť osudnej minulosti.',
            ],
            [
                'name' => 'Na vine sú hviezdy',
                'author' => ['John', 'Green'],
                'category' => 'Romány',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601250',
                'price' => 10.50,
                'stock_count' => 21,
                'year' => 2019,
                'pages_num' => 288,
                'weight' => 0.28,
                'width' => 13.00,
                'height' => 20.00,
                'depth' => 1.80,
                'images' => ['images/books/hviezdy_vino.webp'],
                'description' => 'Odkedy Hazel v trinástich rokoch diagnostikovali rakovinu štítnej žľazy v štvrtom štádiu, pripravovala sa na vlastnú smrť. Potom sa stal medicínsky zázrak a metastázy v pľúcach sa jej zmenšili. Odvtedy nechodí do školy, nemá priateľov a nevie, ako vyzerá normálny život. Je hadičkami pripútaná ku kyslíkovej fľaši a užíva silné lieky, aby sa nádory nerozširovali. Na nenávidenom stretnutí podpornej skupiny pre pacientov s rakovinou však spozná Augusta Watersa. Mladík má štýl, chorobu na ústupe a oči len pre ňu. S ním začne objavovať dosiaľ nepoznaný svet lásky na pomedzí života a smrti.',
            ],
            [
                'name' => 'Chlapec v pásikavom pyžame',
                'author' => ['John', 'Boyne'],
                'category' => 'Romány',
                'language' => 'Slovenčina',
                'publisher' => 'Slovart',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601251',
                'price' => 9.90,
                'stock_count' => 17,
                'year' => 2018,
                'pages_num' => 224,
                'weight' => 0.24,
                'width' => 12.80,
                'height' => 19.70,
                'depth' => 1.50,
                'images' => ['images/books/chlapec_pyzamo.webp'],
                'description' => 'Jedného dňa sa Bruno vráti zo školy a nájde pobalené všetky veci. Jeho otec dostal nové miesto a rodina sa s ním musí odsťahovať ďaleko na zvláštne miesto, kde nemá čo robiť, kde sa nemá s kým hrať. Kam len oko dovidí sa tiahne plot, ktorý ho oddeľuje od čudných ľudí. Bruno je však prieskumník a nezmieri sa s tým, čo vidí. Pri prieskumných cestách pozdĺž plota stretne chlapca, ktorého život a podmienky sú úplne odlišné od jeho.',
            ],
            [
                'name' => 'The Book Thief',
                'author' => ['Markus', 'Zusak'],
                'category' => 'Romány',
                'language' => 'English',
                'publisher' => 'Albatros Media',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601252',
                'price' => 13.50,
                'stock_count' => 16,
                'year' => 2014,
                'pages_num' => 552,
                'weight' => 0.48,
                'width' => 13.00,
                'height' => 19.80,
                'depth' => 3.00,
                'images' => ['images/books/book_thief.webp'],
                'description' => 'HERE IS A SMALL FACT - YOU ARE GOING TO DIE

1939 Nazi Germany. The country is holding its breath. Death has never been busier.
Liesel, a nine-year-old girl, is living with a foster family on Himmel Street. Her parents have been taken away to a concentration camp. Liesel steals books. This is her story and the story of the inhabitants of her street when the bombs begin to fall.

SOME IMPORTANT INFORMATION - THIS NOVEL IS NARRATED BY DEATH',
            ],
            [
                'name' => 'The Kite Runner',
                'author' => ['Khaled', 'Hosseini'],
                'category' => 'Romány',
                'language' => 'English',
                'publisher' => 'Tatran',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601253',
                'price' => 12.90,
                'stock_count' => 13,
                'year' => 2013,
                'pages_num' => 352,
                'weight' => 0.34,
                'width' => 13.00,
                'height' => 19.80,
                'depth' => 2.20,
                'images' => ['images/books/kite_runner.webp'],
                'description' => '',
            ],
            [
                'name' => '1984',
                'author' => ['George', 'Orwell'],
                'category' => 'Romány',
                'language' => 'English',
                'publisher' => 'Slovart',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9780451524935',
                'price' => 11.90,
                'stock_count' => 30,
                'year' => 2015,
                'pages_num' => 328,
                'weight' => 0.29,
                'width' => 12.90,
                'height' => 19.80,
                'depth' => 2.10,
                'images' => ['images/books/1984.webp'],
                'description' => '',
            ],
            [
                'name' => 'Zvieracia farma',
                'author' => ['George', 'Orwell'],
                'category' => 'Romány',
                'language' => 'Slovenčina',
                'publisher' => 'Slovart',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601254',
                'price' => 8.90,
                'stock_count' => 26,
                'year' => 2017,
                'pages_num' => 144,
                'weight' => 0.19,
                'width' => 12.50,
                'height' => 19.50,
                'depth' => 1.20,
                'images' => ['images/books/zvieracia_farma.webp'],
                'description' => '',
            ],
            [
                'name' => 'Vražda v Orient exprese',
                'author' => ['Agatha', 'Christie'],
                'category' => 'Detektívky',
                'language' => 'Slovenčina',
                'publisher' => 'Slovart',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788022205678',
                'price' => 12.50,
                'stock_count' => 18,
                'year' => 2016,
                'pages_num' => 256,
                'weight' => 0.32,
                'width' => 13.50,
                'height' => 20.00,
                'depth' => 2.00,
                'images' => ['images/books/vrazda_expres.webp'],
                'description' => '',
            ],
            [
                'name' => 'Desať malých černoškov',
                'author' => ['Agatha', 'Christie'],
                'category' => 'Detektívky',
                'language' => 'Čeština',
                'publisher' => 'Slovart',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601255',
                'price' => 11.90,
                'stock_count' => 20,
                'year' => 2018,
                'pages_num' => 272,
                'weight' => 0.30,
                'width' => 13.50,
                'height' => 20.00,
                'depth' => 1.90,
                'images' => ['images/books/desat_cernoskou.webp'],
                'description' => '',
            ],
            [
                'name' => 'Sherlock Holmes: Štúdia v červenom',
                'author' => ['Arthur Conan', 'Doyle'],
                'category' => 'Detektívky',
                'language' => 'Čeština',
                'publisher' => 'Tatran',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601257',
                'price' => 10.90,
                'stock_count' => 11,
                'year' => 2016,
                'pages_num' => 192,
                'weight' => 0.25,
                'width' => 13.50,
                'height' => 20.50,
                'depth' => 1.50,
                'images' => ['images/books/sh_studia.webp'],
                'description' => '',
            ],
            [
                'name' => 'Sherlock Holmes: Pes baskervillský',
                'author' => ['Arthur Conan', 'Doyle'],
                'category' => 'Detektívky',
                'language' => 'Čeština',
                'publisher' => 'Tatran',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601258',
                'price' => 10.90,
                'stock_count' => 10,
                'year' => 2016,
                'pages_num' => 224,
                'weight' => 0.27,
                'width' => 13.50,
                'height' => 20.50,
                'depth' => 1.60,
                'images' => ['images/books/sh_pes.webp'],
                'description' => '',
            ],
            [
                'name' => 'Anjeli a démoni',
                'author' => ['Dan', 'Brown'],
                'category' => 'Detektívky',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601259',
                'price' => 13.90,
                'stock_count' => 18,
                'year' => 2015,
                'pages_num' => 616,
                'weight' => 0.52,
                'width' => 13.80,
                'height' => 20.80,
                'depth' => 3.10,
                'images' => ['images/books/anjeli_demoni.webp'],
                'description' => '',
            ],
            [
                'name' => 'Da Vinciho kód',
                'author' => ['Dan', 'Brown'],
                'category' => 'Detektívky',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601260',
                'price' => 13.90,
                'stock_count' => 23,
                'year' => 2015,
                'pages_num' => 592,
                'weight' => 0.50,
                'width' => 13.80,
                'height' => 20.80,
                'depth' => 3.00,
                'images' => ['images/books/davinciho_kod.webp'],
                'description' => '',
            ],
            [
                'name' => 'Meno ruže',
                'author' => ['Umberto', 'Eco'],
                'category' => 'Detektívky',
                'language' => 'Slovenčina',
                'publisher' => 'Slovart',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601261',
                'price' => 16.90,
                'stock_count' => 9,
                'year' => 2014,
                'pages_num' => 536,
                'weight' => 0.58,
                'width' => 14.20,
                'height' => 21.20,
                'depth' => 3.40,
                'images' => ['images/books/meno_ruze.webp'],
                'description' => '',
            ],
            [
                'name' => 'Dracula',
                'author' => ['Bram', 'Stoker'],
                'category' => 'Romány',
                'language' => 'English',
                'publisher' => 'Tatran',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601262',
                'price' => 12.50,
                'stock_count' => 12,
                'year' => 2012,
                'pages_num' => 418,
                'weight' => 0.46,
                'width' => 13.80,
                'height' => 20.80,
                'depth' => 2.70,
                'images' => ['images/books/dracula.webp'],
                'description' => '',
            ],
            [
                'name' => 'Frankenstein',
                'author' => ['Mary', 'Shelley'],
                'category' => 'Romány',
                'language' => 'English',
                'publisher' => 'Tatran',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601263',
                'price' => 11.50,
                'stock_count' => 12,
                'year' => 2011,
                'pages_num' => 280,
                'weight' => 0.29,
                'width' => 13.50,
                'height' => 20.50,
                'depth' => 1.90,
                'images' => ['images/books/frankeinstein.webp'],
                'description' => '',
            ],
            [
                'name' => 'Dvadsaťtisíc míľ pod morom',
                'author' => ['Jules', 'Verne'],
                'category' => 'Romány',
                'language' => 'Slovenčina',
                'publisher' => 'Albatros Media',
                'binding' => 'E-kniha',
                'isbn' => '9788055601264',
                'price' => 7.90,
                'stock_count' => 50,
                'year' => 2026,
                'pages_num' => 368,
                'weight' => 0.00,
                'width' => 0.00,
                'height' => 0.00,
                'depth' => 0.00,
                'images' => ['images/books/dvadsattisic_mil.webp'],
                'description' => '',
            ],
            [
                'name' => 'Čísla neklamú',
                'author' => ['Vaclav', 'Smil'],
                'category' => 'História',
                'language' => 'Čeština',
                'publisher' => 'Slovart',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601306',
                'price' => 21.90,
                'stock_count' => 11,
                'year' => 2026,
                'pages_num' => 416,
                'weight' => 0.72,
                'width' => 16.00,
                'height' => 23.00,
                'depth' => 3.10,
                'images' => ['images/books/cislaneklamu.webp'],
                'description' => '',
            ],
            [
                'name' => 'Stopom až na koniec sveta',
                'author' => ['Peter', 'Hlad'],
                'category' => 'Psychológia',
                'language' => 'Slovenčina',
                'publisher' => 'Tatran',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601307',
                'price' => 13.80,
                'stock_count' => 23,
                'year' => 2026,
                'pages_num' => 248,
                'weight' => 0.33,
                'width' => 13.50,
                'height' => 20.50,
                'depth' => 1.90,
                'images' => ['images/books/stopom.webp'],
                'description' => '',
            ],
            [
                'name' => 'Strieborná elita',
                'author' => ['Dani', 'Francis'],
                'category' => 'Trilery a horory',
                'language' => 'Slovenčina',
                'publisher' => 'Albatros Media',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601308',
                'price' => 19.90,
                'stock_count' => 19,
                'year' => 2026,
                'pages_num' => 192,
                'weight' => 0.66,
                'width' => 18.00,
                'height' => 24.00,
                'depth' => 2.00,
                'images' => ['images/books/elita.webp'],
            ],
            [
                'name' => 'Lordi bolesti',
                'author' => ['Angel', 'Lawson'],
                'category' => 'Trilery a horory',
                'language' => 'Čeština',
                'publisher' => 'Slovart',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601309',
                'price' => 12.90,
                'stock_count' => 15,
                'year' => 2026,
                'pages_num' => 276,
                'weight' => 0.39,
                'width' => 13.50,
                'height' => 20.50,
                'depth' => 2.00,
                'images' => ['images/books/lordibolesti.webp'],
            ],
            [
                'name' => 'Nebojácna',
                'author' => ['Lauren', 'Roberts'],
                'category' => 'Trilery a horory',
                'language' => 'Slovenčina',
                'publisher' => 'Tatran',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601310',
                'price' => 18.60,
                'stock_count' => 17,
                'year' => 2026,
                'pages_num' => 340,
                'weight' => 0.58,
                'width' => 15.00,
                'height' => 22.00,
                'depth' => 2.70,
                'images' => ['images/books/nebojacna.webp'],
                'description' => '',
            ],
        ];

        foreach ($books as $data) {
            $author = Author::where('first_name', $data['author'][0])
                ->where('last_name', $data['author'][1])
                ->firstOrFail();

            $existingBook = Book::where('isbn', $data['isbn'])->first();
            $product = $existingBook?->product ?? Product::firstOrNew(['name' => $data['name']]);
            $description = trim($data['description'] ?? '') !== ''
                ? $data['description']
                : 'Kniha ' . $data['name'] . ' ponúka pútavé čítanie pre všetkých milovníkov kvalitnej literatúry.';

            $product->fill([
                'name' => $data['name'],
                'type' => 'book',
                'price' => $data['price'],
                'stock_count' => $data['stock_count'],
                'category_id' => $categories[$data['category']]->id,
                'description' => $description,
            ]);
            $product->save();

            $book = Book::updateOrCreate(
                ['product_id' => $product->id],
                [
                    'isbn' => $data['isbn'],
                    'publisher_id' => $publishers[$data['publisher']]->id,
                    'language_id' => $languages[$data['language']]->id,
                    'binding_id' => $bindings[$data['binding']]->id,
                    'year' => $data['year'],
                    'pages_num' => $data['pages_num'],
                    'weight' => $data['weight'],
                    'width' => $data['width'],
                    'height' => $data['height'],
                    'depth' => $data['depth'],
                ]
            );

            $book->authors()->sync([$author->id]);

            ProductImage::where('product_id', $product->id)->delete();

            foreach ($data['images'] ?? [] as $imagePath) {
                ProductImage::create([
                    'product_id' => $product->id,
                    'image_path' => $imagePath,
                ]);
            }
        }
    }
}
