<?php

namespace Database\Seeders;

use App\Models\Author;
use App\Models\Binding;
use App\Models\Book;
use App\Models\Category;
use App\Models\Language;
use App\Models\Product;
use App\Models\Publisher;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        // nacitavanie dat do pomocnych poli
        $categories = Category::all()->keyBy('name');
        $publishers = Publisher::all()->keyBy('name');
        $languages = Language::all()->keyBy('name');
        $bindings = Binding::all()->keyBy('name');


        $books = [
            [
                'name' => 'Hobbit',
                'author' => ['J.R.R.', 'Tolkien'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601234',
                'price' => 14.90,
                'stock_count' => 25,
                'year' => 2020,
                'pages_num' => 304,
                'weight' => 0.45,
                'width' => 14.00,
                'height' => 21.00,
                'depth' => 2.50,
            ],
            [
                'name' => 'Pán prsteňov: Spoločenstvo prsteňa',
                'author' => ['J.R.R.', 'Tolkien'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601235',
                'price' => 18.90,
                'stock_count' => 20,
                'year' => 2021,
                'pages_num' => 432,
                'weight' => 0.62,
                'width' => 14.50,
                'height' => 21.50,
                'depth' => 3.20,
            ],
            [
                'name' => 'Pán prsteňov: Dve veže',
                'author' => ['J.R.R.', 'Tolkien'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601236',
                'price' => 18.90,
                'stock_count' => 18,
                'year' => 2021,
                'pages_num' => 448,
                'weight' => 0.64,
                'width' => 14.50,
                'height' => 21.50,
                'depth' => 3.30,
            ],
            [
                'name' => 'Pán prsteňov: Návrat kráľa',
                'author' => ['J.R.R.', 'Tolkien'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601237',
                'price' => 18.90,
                'stock_count' => 17,
                'year' => 2021,
                'pages_num' => 460,
                'weight' => 0.66,
                'width' => 14.50,
                'height' => 21.50,
                'depth' => 3.40,
            ],
            [
                'name' => 'Harry Potter a Kameň mudrcov',
                'author' => ['Joanne', 'Rowling'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601238',
                'price' => 13.90,
                'stock_count' => 30,
                'year' => 2019,
                'pages_num' => 328,
                'weight' => 0.38,
                'width' => 13.50,
                'height' => 20.50,
                'depth' => 2.20,
            ],
            [
                'name' => 'Harry Potter a Tajomná komnata',
                'author' => ['Joanne', 'Rowling'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601239',
                'price' => 13.90,
                'stock_count' => 28,
                'year' => 2019,
                'pages_num' => 352,
                'weight' => 0.40,
                'width' => 13.50,
                'height' => 20.50,
                'depth' => 2.30,
            ],
            [
                'name' => 'Harry Potter a Väzeň z Azkabanu',
                'author' => ['Joanne', 'Rowling'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601240',
                'price' => 14.90,
                'stock_count' => 24,
                'year' => 2020,
                'pages_num' => 392,
                'weight' => 0.43,
                'width' => 13.50,
                'height' => 20.50,
                'depth' => 2.50,
            ],
            [
                'name' => 'Zaklínač: Posledné želanie',
                'author' => ['Andrzej', 'Sapkowski'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Čeština',
                'publisher' => 'Albatros Media',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601241',
                'price' => 15.50,
                'stock_count' => 16,
                'year' => 2018,
                'pages_num' => 288,
                'weight' => 0.36,
                'width' => 13.80,
                'height' => 20.80,
                'depth' => 2.00,
            ],
            [
                'name' => 'Zaklínač: Meč osudu',
                'author' => ['Andrzej', 'Sapkowski'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Čeština',
                'publisher' => 'Albatros Media',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601242',
                'price' => 15.50,
                'stock_count' => 15,
                'year' => 2018,
                'pages_num' => 320,
                'weight' => 0.38,
                'width' => 13.80,
                'height' => 20.80,
                'depth' => 2.10,
            ],
            [
                'name' => 'Letopisy Narnie',
                'author' => ['C.S.', 'Lewis'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'Slovenčina',
                'publisher' => 'Tatran',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601243',
                'price' => 19.90,
                'stock_count' => 14,
                'year' => 2017,
                'pages_num' => 768,
                'weight' => 0.85,
                'width' => 15.50,
                'height' => 22.50,
                'depth' => 4.50,
            ],
            [
                'name' => 'Percy Jackson: Zlodej blesku',
                'author' => ['Rick', 'Riordan'],
                'category' => 'Sci-fi a Fantasy',
                'language' => 'English',
                'publisher' => 'Albatros Media',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601244',
                'price' => 12.90,
                'stock_count' => 22,
                'year' => 2016,
                'pages_num' => 377,
                'weight' => 0.39,
                'width' => 13.00,
                'height' => 19.80,
                'depth' => 2.40,
            ],
            [
                'name' => 'Alchymista',
                'author' => ['Paulo', 'Coelho'],
                'category' => 'Romány',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601245',
                'price' => 10.90,
                'stock_count' => 35,
                'year' => 2018,
                'pages_num' => 192,
                'weight' => 0.22,
                'width' => 12.50,
                'height' => 19.50,
                'depth' => 1.40,
            ],
            [
                'name' => 'Malý princ',
                'author' => ['Antoine', 'de Saint-Exupéry'],
                'category' => 'Romány',
                'language' => 'Slovenčina',
                'publisher' => 'Slovart',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601246',
                'price' => 9.90,
                'stock_count' => 40,
                'year' => 2022,
                'pages_num' => 112,
                'weight' => 0.20,
                'width' => 12.00,
                'height' => 18.00,
                'depth' => 1.20,
            ],
            [
                'name' => 'Pýcha a predsudok',
                'author' => ['Jane', 'Austen'],
                'category' => 'Romány',
                'language' => 'Slovenčina',
                'publisher' => 'Tatran',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601247',
                'price' => 11.50,
                'stock_count' => 19,
                'year' => 2017,
                'pages_num' => 320,
                'weight' => 0.31,
                'width' => 13.00,
                'height' => 20.00,
                'depth' => 2.00,
            ],
            [
                'name' => 'Jane Eyrová',
                'author' => ['Charlotte', 'Brontë'],
                'category' => 'Romány',
                'language' => 'Čeština',
                'publisher' => 'Tatran',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601248',
                'price' => 12.90,
                'stock_count' => 12,
                'year' => 2016,
                'pages_num' => 416,
                'weight' => 0.49,
                'width' => 14.00,
                'height' => 21.00,
                'depth' => 2.80,
            ],
            [
                'name' => 'Búrlivé výšiny',
                'author' => ['Emily', 'Brontë'],
                'category' => 'Romány',
                'language' => 'Slovenčina',
                'publisher' => 'Tatran',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601249',
                'price' => 11.90,
                'stock_count' => 14,
                'year' => 2015,
                'pages_num' => 304,
                'weight' => 0.30,
                'width' => 13.00,
                'height' => 20.00,
                'depth' => 1.90,
            ],
            [
                'name' => 'Na vine sú hviezdy',
                'author' => ['John', 'Green'],
                'category' => 'Romány',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601250',
                'price' => 10.50,
                'stock_count' => 21,
                'year' => 2019,
                'pages_num' => 288,
                'weight' => 0.28,
                'width' => 13.00,
                'height' => 20.00,
                'depth' => 1.80,
            ],
            [
                'name' => 'Chlapec v pásikavom pyžame',
                'author' => ['John', 'Boyne'],
                'category' => 'Romány',
                'language' => 'Slovenčina',
                'publisher' => 'Slovart',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601251',
                'price' => 9.90,
                'stock_count' => 17,
                'year' => 2018,
                'pages_num' => 224,
                'weight' => 0.24,
                'width' => 12.80,
                'height' => 19.70,
                'depth' => 1.50,
            ],
            [
                'name' => 'The Book Thief',
                'author' => ['Markus', 'Zusak'],
                'category' => 'Romány',
                'language' => 'English',
                'publisher' => 'Albatros Media',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601252',
                'price' => 13.50,
                'stock_count' => 16,
                'year' => 2014,
                'pages_num' => 552,
                'weight' => 0.48,
                'width' => 13.00,
                'height' => 19.80,
                'depth' => 3.00,
            ],
            [
                'name' => 'The Kite Runner',
                'author' => ['Khaled', 'Hosseini'],
                'category' => 'Romány',
                'language' => 'English',
                'publisher' => 'Tatran',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601253',
                'price' => 12.90,
                'stock_count' => 13,
                'year' => 2013,
                'pages_num' => 352,
                'weight' => 0.34,
                'width' => 13.00,
                'height' => 19.80,
                'depth' => 2.20,
            ],
            [
                'name' => '1984',
                'author' => ['George', 'Orwell'],
                'category' => 'Romány',
                'language' => 'English',
                'publisher' => 'Slovart',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9780451524935',
                'price' => 11.90,
                'stock_count' => 30,
                'year' => 2015,
                'pages_num' => 328,
                'weight' => 0.29,
                'width' => 12.90,
                'height' => 19.80,
                'depth' => 2.10,
            ],
            [
                'name' => 'Zvieracia farma',
                'author' => ['George', 'Orwell'],
                'category' => 'Romány',
                'language' => 'Slovenčina',
                'publisher' => 'Slovart',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601254',
                'price' => 8.90,
                'stock_count' => 26,
                'year' => 2017,
                'pages_num' => 144,
                'weight' => 0.19,
                'width' => 12.50,
                'height' => 19.50,
                'depth' => 1.20,
            ],
            [
                'name' => 'Vražda v Orient exprese',
                'author' => ['Agatha', 'Christie'],
                'category' => 'Detektívky',
                'language' => 'Slovenčina',
                'publisher' => 'Slovart',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788022205678',
                'price' => 12.50,
                'stock_count' => 18,
                'year' => 2019,
                'pages_num' => 256,
                'weight' => 0.32,
                'width' => 13.50,
                'height' => 20.00,
                'depth' => 2.00,
            ],
            [
                'name' => 'Desať malých černoškov',
                'author' => ['Agatha', 'Christie'],
                'category' => 'Detektívky',
                'language' => 'Slovenčina',
                'publisher' => 'Slovart',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601255',
                'price' => 11.90,
                'stock_count' => 20,
                'year' => 2018,
                'pages_num' => 272,
                'weight' => 0.30,
                'width' => 13.50,
                'height' => 20.00,
                'depth' => 1.90,
            ],
            [
                'name' => 'Smrť na Níle',
                'author' => ['Agatha', 'Christie'],
                'category' => 'Detektívky',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601256',
                'price' => 11.90,
                'stock_count' => 15,
                'year' => 2020,
                'pages_num' => 288,
                'weight' => 0.31,
                'width' => 13.50,
                'height' => 20.00,
                'depth' => 2.00,
            ],
            [
                'name' => 'Sherlock Holmes: Štúdia v červenom',
                'author' => ['Arthur Conan', 'Doyle'],
                'category' => 'Detektívky',
                'language' => 'Čeština',
                'publisher' => 'Tatran',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601257',
                'price' => 10.90,
                'stock_count' => 11,
                'year' => 2016,
                'pages_num' => 192,
                'weight' => 0.25,
                'width' => 13.50,
                'height' => 20.50,
                'depth' => 1.50,
            ],
            [
                'name' => 'Sherlock Holmes: Pes baskervillský',
                'author' => ['Arthur Conan', 'Doyle'],
                'category' => 'Detektívky',
                'language' => 'Čeština',
                'publisher' => 'Tatran',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601258',
                'price' => 10.90,
                'stock_count' => 10,
                'year' => 2016,
                'pages_num' => 224,
                'weight' => 0.27,
                'width' => 13.50,
                'height' => 20.50,
                'depth' => 1.60,
            ],
            [
                'name' => 'Anjeli a démoni',
                'author' => ['Dan', 'Brown'],
                'category' => 'Detektívky',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601259',
                'price' => 13.90,
                'stock_count' => 18,
                'year' => 2015,
                'pages_num' => 616,
                'weight' => 0.52,
                'width' => 13.80,
                'height' => 20.80,
                'depth' => 3.10,
            ],
            [
                'name' => 'Da Vinciho kód',
                'author' => ['Dan', 'Brown'],
                'category' => 'Detektívky',
                'language' => 'Slovenčina',
                'publisher' => 'Ikar',
                'binding' => 'Brožovaná väzba',
                'isbn' => '9788055601260',
                'price' => 13.90,
                'stock_count' => 23,
                'year' => 2015,
                'pages_num' => 592,
                'weight' => 0.50,
                'width' => 13.80,
                'height' => 20.80,
                'depth' => 3.00,
            ],
            [
                'name' => 'Meno ruže',
                'author' => ['Umberto', 'Eco'],
                'category' => 'Detektívky',
                'language' => 'Slovenčina',
                'publisher' => 'Slovart',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601261',
                'price' => 16.90,
                'stock_count' => 9,
                'year' => 2014,
                'pages_num' => 536,
                'weight' => 0.58,
                'width' => 14.20,
                'height' => 21.20,
                'depth' => 3.40,
            ],
            [
                'name' => 'Dracula',
                'author' => ['Bram', 'Stoker'],
                'category' => 'Romány',
                'language' => 'English',
                'publisher' => 'Tatran',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601262',
                'price' => 12.50,
                'stock_count' => 12,
                'year' => 2012,
                'pages_num' => 418,
                'weight' => 0.46,
                'width' => 13.80,
                'height' => 20.80,
                'depth' => 2.70,
            ],
            [
                'name' => 'Frankenstein',
                'author' => ['Mary', 'Shelley'],
                'category' => 'Romány',
                'language' => 'English',
                'publisher' => 'Tatran',
                'binding' => 'Pevná väzba',
                'isbn' => '9788055601263',
                'price' => 11.50,
                'stock_count' => 12,
                'year' => 2011,
                'pages_num' => 280,
                'weight' => 0.29,
                'width' => 13.50,
                'height' => 20.50,
                'depth' => 1.90,
            ],
            [
                'name' => 'Dvadsaťtisíc míľ pod morom',
                'author' => ['Jules', 'Verne'],
                'category' => 'Romány',
                'language' => 'Slovenčina',
                'publisher' => 'Albatros Media',
                'binding' => 'E-kniha',
                'isbn' => '9788055601264',
                'price' => 7.90,
                'stock_count' => 50,
                'year' => 2023,
                'pages_num' => 368,
                'weight' => 0.00,
                'width' => 0.00,
                'height' => 0.00,
                'depth' => 0.00,
            ],
        ];

        foreach ($books as $data) {
            $author = Author::where('first_name', $data['author'][0])
                ->where('last_name', $data['author'][1])
                ->firstOrFail();

            $product = Product::updateOrCreate(
                ['name' => $data['name']],
                [
                    'type' => 'book',
                    'price' => $data['price'],
                    'stock_count' => $data['stock_count'],
                    'category_id' => $categories[$data['category']]->id,
                ]
            );

            $book = Book::updateOrCreate(
                ['product_id' => $product->id],
                [
                    'isbn' => $data['isbn'],
                    'publisher_id' => $publishers[$data['publisher']]->id,
                    'language_id' => $languages[$data['language']]->id,
                    'binding_id' => $bindings[$data['binding']]->id,
                    'year' => $data['year'],
                    'pages_num' => $data['pages_num'],
                    'weight' => $data['weight'],
                    'width' => $data['width'],
                    'height' => $data['height'],
                    'depth' => $data['depth'],
                ]
            );

            $book->authors()->syncWithoutDetaching([$author->id]);
        }
    }
}